const tg = window.Telegram?.WebApp;
if (tg) { tg.ready(); tg.expand(); try { tg.setHeaderColor('#090c11'); tg.setBackgroundColor('#090c11'); } catch(e){} }
const screen=document.getElementById('screen'), avatar=document.getElementById('avatar'), toastEl=document.getElementById('toast');
let dashboard=null, page='home', form={country:'',criteria:'',budget:'',year:'',mileage:'',engine:'',payment:'',timing:'',additional:''}, step=1;
const countries={
  '🇯🇵 Япония':'Япония','🇨🇳 Китай':'Китай','🇰🇷 Корея':'Корея'
};
function headers(){return {'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||''};}
async function api(url,options={}){const r=await fetch(url,{...options,headers:{...headers(),...(options.headers||{})}});const d=await r.json().catch(()=>({error:'Ошибка сервера'}));if(!r.ok)throw new Error(d.error||'Ошибка');return d;}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function money(v){return new Intl.NumberFormat('ru-RU').format(Number(v||0))+' ₽';}
function notify(t){toastEl.textContent=t;toastEl.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toastEl.classList.remove('show'),2200);}
async function load(){if(!tg?.initData){screen.innerHTML='<div class="card"><h3>Откройте приложение в Telegram</h3><p class="muted">Mini App работает внутри Telegram.</p></div>';return;}try{dashboard=await api('/api/dashboard');avatar.textContent=(dashboard.user.name||'NY').slice(0,2).toUpperCase();render();}catch(e){screen.innerHTML=`<div class="card"><h3>Не удалось загрузить приложение</h3><p class="muted">${esc(e.message)}</p></div>`;}}
function setPage(p){page=p;document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));render();}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>setPage(b.dataset.page));document.getElementById('profileBtn').onclick=()=>setPage('profile');
function render(){if(page==='home')home();else if(page==='request')requestPage();else if(page==='requests')requestsPage();else if(page==='partner')partnerPage();else profilePage();}
function home(){const u=dashboard.user;screen.innerHTML=`<section class="hero dark"><div class="eyebrow">NY AUTO</div><h1>Автомобиль, который подходит именно вам.</h1><p>Подберём авто из Японии, Китая или Кореи под ваши задачи, бюджет и пожелания.</p><button class="primary" onclick="startRequest()">🚗 Подобрать автомобиль</button></section><div class="grid2"><button class="action-card" onclick="setPage('requests')"><div class="icon">📋</div><b>Мои заявки</b><small>История обращений</small></button><button class="action-card" onclick="setPage('partner')"><div class="icon">🤝</div><b>${u.is_partner?'Кабинет партнёра':'Стать партнёром'}</b><small>${u.is_partner?'Клиенты и сделки':'Получайте вознаграждение'}</small></button></div><div class="card"><h3>Как всё работает</h3><p class="muted small">1. Вы оставляете параметры автомобиля.<br>2. Мы проверяем варианты и рынок.<br>3. Менеджер связывается с вами и ведёт сделку.</p></div>${u.is_partner?`<div class="stat-grid"><div class="stat"><b>${dashboard.clients.length}</b><span>Ваших клиентов</span></div><div class="stat"><b>${money(u.balance)}</b><span>Ваш баланс</span></div></div>`:`<div class="card"><div class="notice">🤝 Хотите рекомендовать клиентов и получать комиссию? Откройте раздел «Стать партнёром».</div></div>`}`;}
function startRequest(){step=1;form={country:'',criteria:'',budget:'',year:'',mileage:'',engine:'',payment:'',timing:'',additional:''};setPage('request');}
function requestPage(){
 const pct=step===5?100:step*20;
 if(step===1){screen.innerHTML=`<div class="hero"><button class="back" onclick="setPage('home')">← Назад</button><div class="progress"><div style="width:${pct}%"></div></div><div class="step-title">Где ищем автомобиль?</div><p class="muted">Выберите рынок, который вам интересен.</p><div class="chips">${Object.keys(countries).map(k=>`<button class="chip ${form.country===countries[k]?'active':''}" onclick="pick('country','${countries[k]}')">${k}</button>`).join('')}</div>${form.country?`<div class="country-note" style="margin-top:12px">Вы выбрали: <b>${esc(form.country)}</b>. Дальше уточним автомобиль.</div>`:''}<button class="primary" ${!form.country?'disabled':''} onclick="nextStep()">Далее →</button></div>`;return;}
 if(step===2){screen.innerHTML=`<div class="hero"><button class="back" onclick="prevStep()">← Назад</button><div class="progress"><div style="width:${pct}%"></div></div><div class="step-title">Какой автомобиль ищем?</div><p class="muted">Можно указать конкретную модель или описать пожелания своими словами.</p><div class="field"><label>Марка / модель / пожелания</label><input id="criteria" value="${esc(form.criteria)}" placeholder="Например: Toyota RAV4, желательно гибрид"></div><div class="field"><label>Бюджет</label><input id="budget" value="${esc(form.budget)}" placeholder="Например: до 2 500 000 ₽"></div><div class="field"><label>Год выпуска</label><input id="year" value="${esc(form.year)}" placeholder="Например: от 2021"></div><button class="primary" onclick="save2()">Далее →</button></div>`;return;}
 if(step===3){screen.innerHTML=`<div class="hero"><button class="back" onclick="prevStep()">← Назад</button><div class="progress"><div style="width:${pct}%"></div></div><div class="step-title">Состояние и техника</div><p class="muted">Чем точнее параметры, тем быстрее менеджер поймёт задачу.</p><div class="field"><label>Пробег</label><input id="mileage" value="${esc(form.mileage)}" placeholder="Например: до 100 000 км"></div><div class="field"><label>Двигатель</label><input id="engine" value="${esc(form.engine)}" placeholder="Например: бензин / гибрид / 2.0 л"></div><div class="field"><label>Дополнительно</label><textarea id="additional" placeholder="Цвет, привод, комплектация, кузов и любые пожелания">${esc(form.additional)}</textarea></div><button class="primary" onclick="save3()">Далее →</button></div>`;return;}
 if(step===4){screen.innerHTML=`<div class="hero"><button class="back" onclick="prevStep()">← Назад</button><div class="progress"><div style="width:${pct}%"></div></div><div class="step-title">Покупка и сроки</div><p class="muted">Последние вопросы — и заявка готова.</p><div class="field"><label>Способ оплаты</label><div class="chips">${['Наличные','Кредит','Рассрочка'].map(x=>`<button class="chip ${form.payment===x?'active':''}" onclick="pick('payment','${x}')">${x}</button>`).join('')}</div></div><div class="field"><label>Когда нужен автомобиль?</label><input id="timing" value="${esc(form.timing)}" placeholder="Например: в течение 2–3 месяцев"></div><button class="primary" ${!form.payment?'disabled':''} onclick="save4()">Проверить заявку →</button></div>`;return;}
 screen.innerHTML=`<div class="hero"><button class="back" onclick="prevStep()">← Назад</button><div class="progress"><div style="width:100%"></div></div><div class="step-title">Проверьте заявку</div><p class="muted">Ваш Telegram будет прикреплён к заявке автоматически — менеджер сможет открыть ваш профиль даже без username.</p><div class="card"><div class="item"><div class="row"><span class="muted">Страна</span><b>${esc(form.country)}</b></div></div><div class="item"><div class="row"><span class="muted">Автомобиль</span><b>${esc(form.criteria)}</b></div></div><div class="item"><div class="row"><span class="muted">Бюджет</span><b>${esc(form.budget)}</b></div></div><div class="item"><div class="row"><span class="muted">Год</span><b>${esc(form.year)}</b></div></div><div class="item"><div class="row"><span class="muted">Пробег</span><b>${esc(form.mileage)}</b></div></div><div class="item"><div class="row"><span class="muted">Двигатель</span><b>${esc(form.engine)}</b></div></div><div class="item"><div class="row"><span class="muted">Оплата</span><b>${esc(form.payment)}</b></div></div><div class="item"><div class="row"><span class="muted">Срок</span><b>${esc(form.timing)}</b></div></div><div class="item"><span class="muted">Дополнительно</span><div style="margin-top:5px">${esc(form.additional)}</div></div></div><button class="primary" onclick="submitRequest()">✅ Всё верно, отправить</button><button class="secondary" onclick="step=2;render()">✏️ Изменить</button></div>`;
}
function pick(k,v){form[k]=v;render();}function nextStep(){if(!form.country)return notify('Выберите страну');step++;render();}function prevStep(){step=Math.max(1,step-1);render();}
function save2(){form.criteria=document.getElementById('criteria').value.trim();form.budget=document.getElementById('budget').value.trim();form.year=document.getElementById('year').value.trim();if(!form.criteria||!form.budget||!form.year)return notify('Заполните поля');step=3;render();}
function save3(){form.mileage=document.getElementById('mileage').value.trim();form.engine=document.getElementById('engine').value.trim();form.additional=document.getElementById('additional').value.trim();if(!form.mileage||!form.engine||!form.additional)return notify('Заполните поля');step=4;render();}
function save4(){form.timing=document.getElementById('timing').value.trim();if(!form.payment||!form.timing)return notify('Заполните поля');step=5;render();}
async function submitRequest(){try{const contact=(tg.initDataUnsafe?.user?.username?'@'+tg.initDataUnsafe.user.username:(tg.initDataUnsafe?.user?.first_name||'Telegram'));const r=await api('/api/request',{method:'POST',body:JSON.stringify({...form,contact})});await load();notify(`Заявка #${r.request_id} принята`);setTimeout(()=>setPage('requests'),500);}catch(e){notify(e.message);}}
function requestsPage(){const rows=dashboard.requests||[];screen.innerHTML=`<div class="hero"><div class="eyebrow">NY</div><h1>${dashboard.user.is_partner?'Заявки клиентов':'Мои заявки'}</h1><p>Здесь будут все обращения и сделки, созданные через приложение.</p></div><div class="card">${rows.length?rows.map(r=>`<div class="item"><div class="row"><b>Заявка #${r.id}</b><span class="badge">${esc(r.status||'Новая')}</span></div><div class="small muted" style="margin-top:5px">${esc(r.country)} · ${esc(r.criteria)}</div><div class="small" style="margin-top:4px">${esc(r.budget)} · ${esc(r.year)} ${r.deal_id?`· Сделка #${r.deal_id}`:''}</div></div>`).join(''):'<div class="empty">Заявок пока нет.<br><br><button class="primary" onclick="startRequest()">🚗 Подобрать автомобиль</button></div>'}</div>`;}
function partnerPage(){const u=dashboard.user;if(!u.is_partner){screen.innerHTML=`<div class="hero"><div class="eyebrow">ПАРТНЁРСКАЯ ПРОГРАММА</div><h1>Зарабатывайте на рекомендациях.</h1><p>Приглашайте знакомых и клиентов своей ссылкой. Если они оформят автомобиль, сделка будет закреплена за вами.</p><div class="notice" style="margin-top:14px">🤝 Клиент, который впервые открывает приложение по вашей ссылке, автоматически закрепляется за вами.</div><button class="primary" onclick="startPartner()">🤝 Стать партнёром</button></div>`;return;}screen.innerHTML=`<div class="hero"><div class="eyebrow">КАБИНЕТ ПАРТНЁРА</div><h1>Ваши клиенты и сделки.</h1><p>Вся партнёрская статистика — в одном месте.</p></div><div class="stat-grid"><div class="stat"><b>${dashboard.clients.length}</b><span>Клиентов</span></div><div class="stat"><b>${money(u.balance)}</b><span>Баланс</span></div></div><div class="card"><h3>🔗 Ваша ссылка</h3><div class="linkbox">${esc(dashboard.referral_link||'Ссылка появится после настройки BOT_USERNAME')}</div><button class="secondary" onclick="copyLink()">Скопировать</button></div><div class="card"><h3>👥 Клиенты</h3>${dashboard.clients.length?dashboard.clients.slice(0,10).map(c=>`<div class="item"><div class="row"><b>${esc(c.client_id)}</b><span class="badge">${esc(c.status)}</span></div><div class="small muted">Закреплён за вами</div></div>`).join(''):'<div class="empty">Клиентов пока нет.</div>'}</div><div class="card"><h3>🚘 Последние сделки</h3>${(dashboard.deals||[]).length?dashboard.deals.slice(0,10).map(d=>`<div class="item"><div class="row"><b>Сделка #${d.id}</b><span class="badge">${esc(d.status)}</span></div><div class="small">Комиссия: ${money(d.commission)}</div></div>`).join(''):'<div class="empty">Сделок пока нет.</div>'}</div><button class="danger-btn" onclick="stopPartner()">❌ Разорвать партнёрство</button><p class="small muted" style="text-align:center;margin:9px 0">Существующие клиенты, заявки и сделки сохранятся.</p>`;}
async function startPartner(){try{await api('/api/partner/start',{method:'POST'});await load();setPage('partner');notify('Партнёрство активировано');}catch(e){notify(e.message)}}async function stopPartner(){if(!confirm('Разорвать партнёрство? История, клиенты и сделки останутся в системе.'))return;try{await api('/api/partner/stop',{method:'POST'});await load();setPage('partner');notify('Партнёрство отключено');}catch(e){notify(e.message)}}
function copyLink(){if(!dashboard.referral_link)return notify('Ссылка пока не настроена');navigator.clipboard?.writeText(dashboard.referral_link);notify('Ссылка скопирована');}
function profilePage(){const u=dashboard.user;const name=esc(u.name);const username=u.username?`@${esc(u.username)}`:'Username не указан';screen.innerHTML=`<div class="hero"><div class="eyebrow">ПРОФИЛЬ</div><h1>${name}</h1><p>${username}</p></div><div class="card"><div class="contact-card"><div class="contact-avatar">${esc((u.name||'NY').slice(0,2).toUpperCase())}</div><div><b>Telegram</b><div class="small muted">Ваш Telegram ID: ${esc(u.id)}</div></div></div><div class="divider"></div><div class="row"><span class="muted">Статус</span><b>${u.is_partner?'🤝 Партнёр':'👤 Клиент'}</b></div><div class="row" style="margin-top:12px"><span class="muted">Баланс</span><b>${money(u.balance)}</b></div></div><div class="card"><h3>📞 Поддержка</h3><p class="small muted">Напишите менеджеру прямо из приложения.</p><textarea id="supportText" placeholder="Ваш вопрос..."></textarea><button class="primary" onclick="support()">Отправить сообщение</button></div>`;}
async function support(){const t=document.getElementById('supportText').value.trim();if(!t)return notify('Напишите сообщение');try{await api('/api/support',{method:'POST',body:JSON.stringify({text:t})});document.getElementById('supportText').value='';notify('Сообщение отправлено');}catch(e){notify(e.message)}}
load();
